### ISSUE TITLE
Question: Does EventSource Plus have the same browser support as EventSource?

### ISSUE THREAD

**Issue by sandroboehme** [joshmossas/event-source-plus#22]
The documentation states "Runs in browsers". Does that mean it is as widely supported as the EventSource interface itself?

**Comment by joshmossas** [comment]
Hey @sandroboehme,

Yes I believe that EventSourcePlus will run in all the browsers that support EventSource (although I haven't thoroughly investigated that claim)

Under the hood, EventSourcePlus uses [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) alongside [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) (specifically the [getReader()](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/getReader) method). So it'll work in any browser that supports those APIs, which is all modern browsers. 

If you need to support Internet Explorer you'll have to make use of polyfills, although I believe the same is true for `EventSource`

**Comment by joshmossas** [comment]
It would be worthwhile to add a note about browser support to the README
