### ISSUE TITLE
Please add license file and copyright notice

### ISSUE THREAD

**Issue by SEQUOiA87** [joshmossas/event-source-plus#3]
Hey @joshmossas.

Greatly appreciating your work! 

I would like to use this lib as it seems to work pretty well and I couldn't find a better alternative with such a nice feature set, yet using modern helpers to be this easy to use.

That being said, it would be nice if you could add a license file and copyright notice. :)

Thanks a lot in advance!

**Comment by joshmossas** [comment]
Hey @SEQUOiA87 thanks for the kind words!

I've added a LICENSE file to the root of the directory. Everything is MIT licensed so feel free to use it however.

**Comment by SEQUOiA87** [comment]
Thanks @joshmossas, appreciated!
